# Generated by Django 5.1.3 on 2024-11-11 14:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('holding_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lead_time', models.IntegerField()),
                ('minimum_order_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Skate_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateField()),
                ('production_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ComponentSubComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_needed', models.FloatField()),
                ('parent_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_relationships', to='App.component')),
                ('sub_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_components', to='App.component')),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='sub_components',
            field=models.ManyToManyField(blank=True, related_name='parent_components', through='App.ComponentSubComponent', to='App.component'),
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_on_hand', models.IntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.component')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('gross_requirements', models.FloatField()),
                ('net_requirement', models.FloatField(editable=False)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_release_date', models.DateField(editable=False)),
                ('planned_order_receipt', models.IntegerField(editable=False)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.component')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.stock')),
            ],
        ),
    ]
