# Generated by Django 5.1.3 on 2024-11-15 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='components/images/'),
        ),
        migrations.AlterField(
            model_name='componentsubcomponent',
            name='parent_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_component', to='App.component'),
        ),
        migrations.AlterField(
            model_name='componentsubcomponent',
            name='quantity_needed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='gross_requirements',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='net_requirement',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='componentsubcomponent',
            constraint=models.UniqueConstraint(fields=('parent_component', 'sub_component'), name='unique_subcomponent_for_component'),
        ),
    ]
